services:
  - name: reminder-bot
    env:
      - key: RENDER
        value: "true"
  - name: static
    build_command: pip install -r requirements.txt
    env: []
    shell: none
  - name: web
    build_command: null
    env: []
    shell: python bot.py
